name: marvel_comic_app
description: App to show marvel characters and comics
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.0

dependencies:
  convert: ^3.1.1
  crypto: ^3.0.2
  dio: ^5.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  hooks_riverpod: ^2.3.2
  intl: ^0.17.0
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  generate: true
